FROM node:16.7.0 as base

ENV NODE_ENV=production

RUN chown node:node /home/node

WORKDIR /home/node

COPY package*.json ./

RUN npm config list \
    && npm ci \
    && npm cache clean --force

EXPOSE 5000

FROM base as dev

ENV NODE_ENV=development
# required for wait-for script
RUN apt-get -q update && apt-get -qy install netcat 

ENV PATH=/home/node/node_modules/.bin:$PATH

WORKDIR /home/node

RUN npm install -D
WORKDIR /home/node/app

USER node
CMD ["npm","run","start:dev"]

FROM base as prod
WORKDIR /home/node/app

COPY . .

USER node
CMD ["npm","start"]